[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1.15"  # Templating for SSR
tokio = { version = "1", features = ["full"] }
diesel = { version = "2.0", features = ["postgres", "r2d2"] }
dotenv = "0.15"
